### ISSUE TITLE
Baw client parity

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#191]
(M) = Migrated

List of pages to replicate in workbench-client before parity is reached with baw server:

- [ ] Recent Recordings
  - [ ] (M) Home (`/listen`) https://github.com/QutEcoacoustics/workbench-client/issues/206
  - [ ] (M) Listen (`/listen/:recordingId`) https://github.com/QutEcoacoustics/workbench-client/issues/207
- [ ] Library
  - [ ] (M) Home (`/library`) https://github.com/QutEcoacoustics/workbench-client/issues/208
  - [ ] (M) Library Item (`/library/:recordingId/audio_events/:audioEventId`) https://github.com/QutEcoacoustics/workbench-client/issues/209
- [ ] (M) Visualize (`/visualize`) https://github.com/QutEcoacoustics/workbench-client/issues/210
- [ ] Citizen Science
  - [ ] (M) About Study (`/citsci/:studyName`) https://github.com/QutEcoacoustics/workbench-client/issues/215
  - [ ] (M) Listen (`/citsci/:studyName/listen`) https://github.com/QutEcoacoustics/workbench-client/issues/216
  - [ ] (M) Listen Id (`/citsci/:studyName/listen/:sampleNum`) https://github.com/QutEcoacoustics/workbench-client/issues/217
  - [ ] (M) Responses (`/citsci/:studyName/responses`) https://github.com/QutEcoacoustics/workbench-client/issues/218
- [ ] Analysis Jobs
  - [ ] (M) List (`/audio_analysis`)  https://github.com/QutEcoacoustics/workbench-client/issues/211
  - [ ] (M) New (`/audio_analysis/new`) https://github.com/QutEcoacoustics/workbench-client/issues/212
  - [ ] (M) Details (`/audio_analysis/:analysisJobId`) https://github.com/QutEcoacoustics/workbench-client/issues/213
  - [ ] (M) Analysis Results (`/audio_analysis/:analysisJobId/results:path*?`) https://github.com/QutEcoacoustics/workbench-client/issues/214

**Comment by atruskie** [comment]
Priority:

1. Visualize
2. CS
3. Analysis Jobs
4. Library

Do not start: Listen. More planning needed.
